### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by melflynn** [melflynn/BarkedIn#2]
# User Auth
## Functionality
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation
### Before Login
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
### After Login
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
## Style
- [x] Things should be positioned correctly.
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] Remove Redux logger and all console.log()'s from production
## Seeds
- [x] Adequate and appropriate seeds

**Comment by melflynn** [comment]
@samwalker191 I have also updated my backend routes to include a GET /api/users route for checking the presence of an existing email in the database

**Comment by samwalker191** [comment]
Nice! Just a few things:

- [x] Login form should also have a demo login button
- [x] Ideally, going to a random route should redirect back to the root route, or to feed if logged in.

**Comment by melflynn** [comment]
Updated to add demo login to login page. Also removed logger from main branch. Can you let me know where you are being redirected to on a random route? On my end it does go to "/" if logged out and "/feed" if logged in. 

Thanks!

**Comment by samwalker191** [comment]
Looks good! The random route is just from me typing into the search bar. but it redirects now
